---
title: "Untitled"
author: 'test'
date: "08/05/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide', message=FALSE, warning=FALSE}
# imports
library(caret)
library(fossil)
```

```{r}
source("hello.R", local = knitr::knit_global())
cluster <- as.factor(c(1,1,1,1,1,2,1,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2))
truth <- as.factor(c(2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1))
x <- labelremap(cluster, truth)
```


```{r}
a <- c(1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2)
b <- c(1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2)

source("hello.R", local = knitr::knit_global())
x <- labelremap(as.factor(a), as.factor(b))

x
```


```{r}
rand.index(as.numeric(cluster), as.numeric(truth))
adj.rand.index(as.numeric(cluster), as.numeric(truth))
```

```{r}
rand.index(as.numeric(x), as.numeric(truth))
adj.rand.index(as.numeric(x), as.numeric(truth))
```

# fix bug when using income 1 & 2
```{r}
# a <- as.factor(c(1,1,2,2,1,2,1,1,2,2,1,2,2,1,2,2,2,1,2,1,2,2,2,1,1,1,1,2,2,1,2,2,1,1,2,1,1,1,1,1,2,2,1,2,2,1,2,1,2,1,1,2,1,1,2))
# b <- as.factor(c(1,3,3,3,1,3,1,1,3,3,1,3,3,1,3,3,3,1,3,1,3,3,3,1,1,1,1,3,3,3,3,3,3,1,3,1,1,1,1,1,3,3,1,3,3,1,3,1,3,1,1,3,1,1,3))

source("hello.R", local = knitr::knit_global())

a <- as.factor(result$result)
b <- as.factor(result$income)
x <- labelremap(a,b)
# print(x)
```

